### ISSUE TITLE
TP1 - Première Issue

### ISSUE THREAD

**Issue by ProjetInfoIlo** [PolytechLyon/2019-isi3-graph-ensuque_ciavaldini#4]
Ceci est la première Issue pour le TP1.
Le rapport est inclu dans le projet, dans le fichier rapport.md précisément (et il y a même des images !).

Je mets nos noms même si c'est inutil :
ENSUQUE Elie - CIAVALDINI Ilorian

**Comment by Slashgear** [comment]
⚠️ Pas touche à mes commentaires

- 👍 Rapport
-  [ ] Quel est la différence entre une `List` et un `Set`en Java ?

ici devrait-on retourner une List ou Set ?

https://github.com/PolytechLyon/2019-isi3-graph-ensuque_ciavaldini/blob/33f38033a223f6afb21a1ff4d1516a14da4f4c24/src/main/java/graph/Graph.java#L47-L52

- 👍 pour les itérateurs
- [ ] pourquoi ici le mot `public` est inutile ? 

https://github.com/PolytechLyon/2019-isi3-graph-ensuque_ciavaldini/blob/33f38033a223f6afb21a1ff4d1516a14da4f4c24/src/main/java/graph/IDirectedGraph.java#L12

Répondez moi directement ici

**Comment by ProjetInfoIlo** [comment]
Quelle est la différence entre une List et un Set en Java ?
- Un Set n'autorise qu'une seule occurence d'un même objet, et même plus précisément, cette occurence est basée sur le HashCode de l'objet à inserer. Ainsi, deux objets identiques ne peuvent pas être tout deux ajoutés au Set (un seul sera présent), et deux objets différents mais avec le même HashCode ne pourront pas non plus être tout deux présents. Une List quant à elle accepte les multiples occurrences des mêmes objets.
La deuxième différence joue sur la notion d'ordre : une liste conserve l'ordre dans lequel les éléments sont placés. On A une notion de premier, denier et n-ième. Dans le cas des Set, ce n'est pas possible de prendre le premier ou le dernier. Même si techniquement, itérer deux fois sur le même Set suivra le même ordre, il n'y a aucune contrainte, et il serait parfaitement possible d'itérer deux fois sur un même Set sans que l'ordre d'itération ne soit le même.
Dans la méthode, renvoyer un Set serait suffisant car l'ordre des éléments renvoyés n'a pas d'importance, et il n'y aura pas de doublons de Node.

Pourquoi le 'public' est-il inutile ici ?
- Le mot clé public est redondant sur une interface. La méthode n'étant pas encore implémentée, il n'y a pas forcément besoin de spécifier son accès, mais surtout, l'implémentation des interfaces requiert que les méthodes soient public, pour que les autres classes puissent utiliser l'interface. (Ce qui est le principe d'une interface)

En ce qui est de la documentation partielle, elle a été complétée.

**Comment by Slashgear** [comment]
Très bien, TP terminé 👏
